### ISSUE TITLE
`hiddenBonuses` collapsible doesn't change height when bonuses are added/removed

### ISSUE THREAD

**Issue by jktrn** [jktrn/screenshot-impact#24]
![Image](https://github.com/jktrn/screenshot-impact/assets/71956291/074dec82-51c1-4b5e-b030-561cb395eabc)

![Image](https://github.com/jktrn/screenshot-impact/assets/71956291/1fca234d-3328-44eb-9443-0e9cdb1fdbda)

**Comment by nilocnus** [comment]
Current PR draft refreshes the collapsible to auto-update and also fixes an issue with an opening animation bug that was found but not declared within the original thread.

Draft has a minor issue with extraneous animations upon updating the hiddenBonuses collapsible. May or may not be desired

**Comment by jktrn** [comment]
Resolved.
