### ISSUE TITLE
`<ActiveSkillsSelect>` doesn't change whenever C3 or C5 is selected

### ISSUE THREAD

**Issue by jktrn** [jktrn/screenshot-impact#25]
Note: whenever a constellation is active and the user switches characters, it DOES update `<ActiveSkillsSelect>`. However, the "update" literally changes the select option to "Lv13" instead of simply adding on top of the selection (e.g. even though the user selects "Lv8" in the dropdown, the +3 effect still occurs and it results in "Lv11" appearing).

**Comment by nilocnus** [comment]
Proposed solution:

`<ActiveSkillsSelect>` should be selectable from a value from 1-10. Have another copy of the former object, for the sake of the solution argument let's notate this `<ActiveSkillsSet>`.

`<ActiveSkillsSet>` should not be an interactive element that the user is capable of selecting and altering. However, it contains levels ranging from 1-15. It should auto-update its own value to match any value that has been updated within `<ActiveSkillsSelect>`. Then, append any bonuses to its value that may be applicable. Check if C3 or C5 is enabled, check if bonuses from other characters are active (such as Childe's A1 passive), and then retain its final value. Anytime the `<ActiveSkillsSelect>` is updated, this process may be repeated in sequence so the user cannot manually revert levels after, say a constellation has been updated.

`<ActiveSkillsSet>` is the one that should be displayed and used in the background for the calculations. `<ActiveSkillsSelect>` should be the selectable element that the user may interact with.

**Comment by jktrn** [comment]
Switched to [shadcn](https://ui.shadcn.com/docs/components/select)'s `Select` component and it magically fixed itself. Will resolve once committed!

**Comment by jktrn** [comment]
Resolved with [`da84b8a`](https://github.com/jktrn/screenshot-impact/commit/da84b8a7f328c3102320680b21076dc1abc730db).

**Comment by jktrn** [comment]
False alarm, it's back...
We need to figure out how to update this component when the value it's reading is manipulated outside of it.

**Comment by jktrn** [comment]
Resolved.
